nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:4200']
        allow_methods: ['GET', 'POST', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type'] 
        max_age: 3600
    paths:
        '^/': null
